name: ds
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - notebook
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - scipy
  - statsmodels
  - pip
  - pip:
      - "openbb[all]"
